version: '3.4'
services:
### MySQL Container
    mysql:
        container_name: u2l_db
        build:
            context: ./mysql
            
            args:
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                - MYSQL_PORT=${MYSQL_PORT}
        env_file: .env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            
        ports:
            - 3306:3306

    u2l_backend:
        container_name: u2l_backend
        build: 
            context: ./u2l_backend
        #command: python3 ./app.py
        ports:
            - 5000:5000
        depends_on:
          - mysql
          - redis
          #- worker
       

    redis:
       container_name: redis
       image: redis
       ports:
           - 6379:6379

    # worker:
    #   container_name: celery
    #   build:
    #    context: ./u2l_backend
    #   restart: always
    #   #entrypoint: celery
    #   #command: celery -A celery_setup worker --loglevel=info -n celeryTaskWorker
    #   user: nobody
    #   depends_on:
    #      - redis


    u2l_frontend:
        container_name: u2l_frontend
        build:
            context: ./u2l_frontend
            
        ports:
            - 8081:80
        depends_on:
          -  u2l_backend
             
             
